apiVersion: v1
kind: ReplicationController
metadata:
  name: my-nginx
spec:
  replicas: 3
  selector:
    app: my-nginx
    version: 2.3.20
  template:
    metadata:
      labels:
        app: my-nginx
        version: 2.3.20
    spec:
      containers:
      - image: kubernetes.io/hostname=10.245.1.3
        name: my-nginx
      imagePullPolicy: PullAlways
